### ISSUE TITLE
Error when accessing the frame props of alpha clip

### ISSUE THREAD

**Issue by YomikoR** [AkarinVS/L-SMASH-Works#16]
Suppose `alpha.png` has an alpha channel (e.g. created from Windows screenshot).

```python
# Python 3.9.7 embedded
import vapoursynth as vs # R56 portable
clip = vs.core.lsmas.LWLibavSource('alpha.png') # vA.3g
frame = clip.get_frame(0)
print(frame.props) # Has an alpha frame
print(frame.props['_Alpha'].props) # Python crashes
```
The PNG:
![alpha](https://user-images.githubusercontent.com/64504948/135580505-9f930f72-2e7d-4cb4-82ac-75e3743cde08.png)

**Comment by AkarinVS** [comment]
Thanks for the bug report. Will update vA.3g builds soon.

**Comment by YomikoR** [comment]
Thanks. But having python crashed because of it still looks weird. Do you think it's a bug of VS?

**Comment by AkarinVS** [comment]
Not a bug of VS. It's a typo in lsmas that accidentally used propSetFrame
(instead of propSetInt) to set the _ColorRange property to 0, which is
interpreted as a NULL pointer.
therefore when VS tries to create the Python props dict, it will try to
create a VideoFrame from a NULL pointer, triggering a crash.
